// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggiqwnbvmadxiqfsjorv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnaXF3bmJ2bWFkeGlxZnNqb3J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMzQxMzAsImV4cCI6MjA2MzgxMDEzMH0.wBFIjUVMv5P6yfwwtMtZN3mYGjnP75jPToUPaDUvs9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);